from qq275860560/base

MAINTAINER jiangyuanlin@163.com

# 下载
RUN curl -o /usr/local/ngrinder-master.war   https://github.com/naver/ngrinder/releases/download/ngrinder-3.4.2-20180830/ngrinder-controller-3.4.2.war

RUN curl -o /etc/rc.local https://raw.githubusercontent.com/qq275860560/ngrinder-master/master/src/main/centos/etc/rc.local && chmod +x /etc/rc.local


		